### ISSUE TITLE
When the timer is initialized, the ARR register will be miscalculated.

### ISSUE THREAD

**Issue by OcenYu** [STMicroelectronics/STM32CubeF4#165]
**Describe the set-up**
 *  IDE: CubeMX 6.9.2

**Describe the bug**
When the timer is initialized, the ARR register will be miscalculated.

**How To Reproduce**
1. Use CubeMX 6.9.2 generate code on STM32G474VCT6

**Screenshots**
![image](https://github.com/STMicroelectronics/STM32CubeF4/assets/52883446/50f574e1-867b-4991-b0c1-bbe1dd291f76)

**Comment by TOUNSTM** [comment]
Hello @OcenYu,

sorry for the delayed response. Please try using the latest CubeMX version 6.13.0. If the problem persists, kindly submit the issue in the [ST Community](https://community.st.com/s/question/0D53W00000JhsU4SAJ/stm32cubemx-ide-issue-throws-warning-when-using-macros) in the CubeMX related section.

Now, as this issue is not directly related to some software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to our ecosystem (namely the Cube MX tool), please allow me to close it.
Thank you again for your report. We are looking forward to reading from you again.

Kind regards,
