### ISSUE TITLE
stm32f407vgt6 freertos ethernet code generated from cubemx hang out indefinetly

### ISSUE THREAD

**Issue by learncodingforweb** [STMicroelectronics/STM32CubeF4#179]
**Describe the set-up**
Board STM32F407VGT6 Discovery board
STM32CubeIDE
Version: 1.16.0
Build: 21983_20240628_1741 (UTC)
OS: Linux, v.6.8.0-40-generic, x86_64 / gtk 3.24.33
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.11+9
Java version: 17.0.11
STM32CubeMX Version 6.12.0

**Describe the bug**
(HAL_ETH_Transmit_IT(&heth, &TxConfig) == HAL_OK) {
    while(osSemaphoreAcquire(TxPktSemaphore, TIME_WAITING_FOR_INPUT)!=osOK)

    {
    }

    HAL_ETH_ReleaseTxPacket(&heth);
  } else {
    pbuf_free(p);
  }
it wait indefinitely on 	configASSERT( pxQueue->uxItemSize == 0 );?
Behaviour is unpredictable. do not know when this problem comes.

**How To Reproduce**
select stm32f407vgt6 , enable RMII, enable freertos and lwip stack.
For more details, See repository [https://github.com/learncodingforweb/stm32f407_httpd_freertos](https://github.com/learncodingforweb/stm32f407_httpd_freertos)

**Comment by ASEHSTM** [comment]
ST Internal Reference: 189333

**Comment by ASEHSTM** [comment]
Hello @learncodingforweb,

The code generated from CubeMX is not aligned with the latest version of the Cube firmware. This issue has been tracked internally and will be fixed in the upcoming release of CubeMX. Therefore, please allow me to close this issue. 

Thank you for your understanding.
With Regards,
