### ISSUE TITLE
ASSERTION FAILED during RCC initialization with STM32CubeMX + FreeRTOS generated code

### ISSUE THREAD

**Issue by the78mole** [STMicroelectronics/STM32CubeF4#18]
In function HAL_RCC_ClockConfig, which in turn is called by SystemClockConfig and main.c from CubeMX generated code (at least when FreeRTOS is using a timer for systick) 

https://github.com/STMicroelectronics/STM32CubeF4/blob/5d01400afd60410f6e049cbd19179a67d44d53fd/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c#L713

here the default value of uwTickPrio is used, which is set (possibly by intention) to an invalid value:

https://github.com/STMicroelectronics/STM32CubeF4/blob/a86ecaa2fb63029596ba7dabadab2d9c2c139560/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c#L95

This results in some unintended assertion.

![image](https://user-images.githubusercontent.com/7723396/82347746-4eba6900-99f8-11ea-8a8e-e08a29d5074d.png)

In my config, TIM14 is used as the SysTick source.

My hotfix to this issue is, to set uwTickPrio to a valid value in user code section between HAL_Init and SystemClockConfig.

![image](https://user-images.githubusercontent.com/7723396/82348194-d0aa9200-99f8-11ea-98c5-5bd989f9feb5.png)

**Comment by RKOUSTM** [comment]
Hi @the78mole,

Thank you for your contribution. According to our analysis, this issue is rather related to CubeMX, may I ask you to submit it to the ST Community in the dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx)? There, you will hopefully find people from our CubeMX development teams who will take in charge your request.

Thank you again for your contribution. 

With regards,
