### ISSUE TITLE
USB Composite Device: USB CDC + USB MSC (or other combinations)  (Feature Request)

### ISSUE THREAD

**Issue by jrahlf** [STMicroelectronics/STM32CubeF4#47]
Hi,

can you add composite USB (for example USB MSC + USB CDC) driver to the Middlewares?

I am sure many users will appreciate this. There are only few and mostly outdated/incomplete examples how to get USB MSC + USB CDC working as a composite device.

Regards

**Comment by ALABSTM** [comment]
Hi @jrahlf,

Please excuse the delay we may take sometimes to reply. Regarding your request, I let @CHAMSTM comment.

With regards,

**Comment by CHAMSTM** [comment]
Hi @jrahlf ,

A USB Device Composite example can be constructed based on today's available library and applications provided by ST through some rework.
But in order to provide a "clean" and generic support of composite devices, a major change is required on USB Device library.
We are currently working on this major change and will be releasing it on GitHub as soon as it is ready.

Kind Regards,

**Comment by mrhodel** [comment]
Any progress on this? Maybe an estimate as to when it will be available?
We're at a crossroads right now and having MSC+VCP USB interface would save us a lot of work and save a connector in the finished product.

A reference or link to the "library/applications provided by ST" that we could re-work would be helpful.

**Comment by kjsdf7wr3** [comment]
@alambe94 That looks awesome, is it still experimental?

**Comment by ALABSTM** [comment]
Hi,

The request has been internally logged and forwarded to our USB team. We will get back to you once there is something new.

@alambe94, thank you for the proposal.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 126915

**Comment by ericshufro** [comment]
Any update? Looking for dual cdc, dfu, and hid.

**Comment by mrhodel** [comment]
Has there been any progress on this feature?

**Comment by ALABSTM** [comment]
Hi there,

Hope you all are doing well. Just to let you know that composite classes are now supported by ST's USB Device library since version **2.10.0**. This version has been integrated into version **1.27.0** of the STM32CubeF4 firmware.

A couple of **examples** have been published within the STM32CubeH7 firmware on a **specific branch** of the repo. You can refer to [this](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions/18) post for more details.

Hope this addresses you request. Thank you again for having raised the point.

With regards,

**Comment by ericshufro** [comment]
Thank you for letting me know.  Unmodified the USB code for support a while
back. Perhaps in the future I'll have an opportunity to try the official
support.

All the best

E
