### ISSUE TITLE
HARDFAULT when sbmus is enabled

### ISSUE THREAD

**Issue by gionag** [STMicroelectronics/STM32CubeF4#66]
Hi,

scenario:
StmCubeIDE 1.6.0
STM32Cube FW_F4 V1.26.0
both with P/N STM32F401RE / STM32F446VE (but i guess is a shared problem all across the line)

how to reproduce:
starting from a fresh stm32 project under cube ide,
just activate smbus two-wire-mode under I2C.

-> generate the Code
-> build the code
-> upload to the board (debug)

as soon as you start the program an hardfault will trigger.
the fault analyzer report a d DIVBYZERO.

Seems related to an initialization problem and the missing paramenter under Init.ClockSpeed.

Not done further investigation, but if i set "manually" the hsmbus1.init.clockspeed = 100000 then the code compile, no hardfault triggered, but the peripheral don't work.

Thanks

**Comment by ASELSTM** [comment]
Hi @gionag,

The HardFault is due to a division by zero within the `SMBUS_SPEED_STANDARD(pclk1, hsmbus->Init.ClockSpeed)`  instruction called during the SMBUS initialization `HAL_SMBUS_Init()`. The `hsmbus->Init.ClockSpeed` is not initialized and keeps its default value which is zero.  Given that the `SMBUS_SPEED_STANDARD` macro will divide  `pclk1`  the `hsmbus->Init.ClockSpeed` a HardFault will be generated since `hsmbus->Init.ClockSpeed` is equal to zero.

This issue is rather related to the CubeIDE tool and particularly to the CubeMx tool used for the generation of the initialization code. Actually, aspects related to tools are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the **CubeMX** dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) and  **CubeIDE** dedicated [section](https://community.st.com/s/topic/0TO0X000000y2j7WAA/stm32cubeide). There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue.

As this issue is not directly related to software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to ecosystem (CubeMX tool, CubeIDE tool), please allow me to close it. Thank you for your comprehension.

With regards,
