### ISSUE TITLE
FreeRTOS and LWIP

### ISSUE THREAD

**Issue by Ddh012345dhD** [STMicroelectronics/STM32CubeF4#71]
I want to create a websever to control 1 led beside that I want to control another led in another task but Freertos and lwip not work.

**Comment by RKOUSTM** [comment]
Hi @Ddh012345dhD,

Welcome to our GitHub organization and thank you for your contribution.

In order to allow a better analysis of this problem, could you please give us more details about on how to reproduce it and could you please give us the name of the project that is used to reproduce this issue.

Thank you again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
Hi @Ddh012345dhD,

I hope you are fine. Any new feedback regarding this issue?

With regards,

**Comment by RKOUSTM** [comment]
Hi @Ddh012345dhD,

I hope you are doing well. Any new comments to move this discussion forward?

with regards,

**Comment by RKOUSTM** [comment]
Hi @Ddh012345dhD, 

Please allow me to close this thread. You can reopen it at any time if you have details to provide us to help you.

Thank you for your comprehension and thank you once more for your contribution

With regards,
